################################################################################
# Config for stylua, ref: https://github.com/JohnnyMorganz/StyLua
################################################################################
column_width = 120
line_endings = "Windows"
indent_type = "Tabs"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"